services:

  node-base:
    build:
      context: ./base-node-image
    image: nexe-node-base:latest

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - frontend_dist:/app/dist
    depends_on:
      - gateway
    networks:
      - frontend

  gateway:
    build: ./gateway
    expose:
      - "8080"
    env_file:
      - ./gateway/.env
    depends_on:
      - node-base
      - auth-service
    networks:
      - backend
      - frontend

  auth-service:
    build: ./auth-service
    expose:
      - "8081"
    depends_on:
      - node-base
    volumes:
      - auth_data:/app/data
    networks:
      - backend

  user-management-service:
    build: ./user-management
    expose:
      - "8082"
    depends_on:
      - node-base
    volumes:
      - user_data:/app/data
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
  
  frontend:
    name: frontend
    driver: bridge

volumes:
  auth_data:
  user_data:
  frontend_dist:
